[package]
name = "ff-bench-atime"
version = "0.1.0"
edition = "2024"

[dependencies]
ff = {path = "../ff"}
anyhow = "1.0.99"
clap = { version = "4.5.46", features = ["derive"] }
indicatif = "0.18.0"
libc = "0.2.175"
nix = { version = "0.30.1", features = ["mount"] }
statistical = "1.0.0"
