[package]
name = "ff-bench-fsync"
version = "0.1.0"
edition = "2024"

[dependencies]
ff = {path = "../ff"}
anyhow = "1.0.99"
clap = { version = "4.5.46", features = ["derive"] }
indicatif = "0.18.0"
libc = "0.2.175"
nix = "0.30.1"
core_affinity = "0.8.3"
fastrand = "2.3.0"
