name: Rust
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Add Cargo to PATH
      run: echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"
    - uses: actions/checkout@v4
    - name: Build
      run: cargo check
    - name: Run (non-root) tests
      run: cargo test
    - name: Run (root) tests
      run: sudo -E cargo test run_as_root -- --ignored
    - name: Run clippy
      run: cargo clippy -- -D warnings
